### ISSUE TITLE
Throw an error if the file size exceeds the limit

### ISSUE THREAD

**Issue by chinesedfan** [rollup/rollup-plugin-url#14]
I just want this plugin to prevent other developers from introducing large files, instead of generating public links.

Can you add an option for this, or other suggestions for me?

**Comment by Ashot-KR** [comment]
hi @chinesedfan 
> to prevent other developers from introducing large files

can you explain this more precisely?
and what exactly option do you need and what it should do?

**Comment by chinesedfan** [comment]
@Ashot-KR Now this plugin will generate links for large image files and base64 for small ones. I hope it can simply throw an error once large files were detected.

**Comment by Ashot-KR** [comment]
I think such functionality shouldn't be in this plugin. The only purpose of `rollup-plugin-url` is to generate public links for files.

But your idea is good for plugin which will take care of file sizes.

Creation of this functionality in specific plugin has some advantages:
1. it can be configured on any files (even on `.js` or `css` files)
2. configuration will be more flexible

I like your idea. Probably i will create such plugin if i have some free time for this
