### ISSUE TITLE
could rollup can bundle es2015_module and commonjs_module at both

### ISSUE THREAD

**Issue by tgxpuisb** [rollup/rollup-plugin-url#2]
I'm sorry to ask you this question at here, but I was troubled by this question for a long time
I found you at other registry and I know you are very proficient in rollup, SO, I hope you can help me to resolve this question, thanks a lot
this question is: can I use rollup to bundle es2015_module and commonjs_module at the same file
just like:

```
import { foo } from './foo.js'
const bar = require('./bar.js')

// other code
```

I used rollup-plugin-commonjs but it will throw errors when run bundling-script

**Comment by Swatinem** [comment]
why would you want to do that? Just stick to es2015 imports all the way.
