### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by lukastaegert** [rollup/rollup-plugin-url#23]
@shellscape Updated some dependencies to solve security issues, would be nice if one of @Ashot-KR or @Swatinem could publish an updated version as you are the ones with publishing rights.

**Comment by Swatinem** [comment]
> as you are the ones with publishing rights.

I just added you.


I wasn’t involved in this project for years, so I don’t really know if this is a patch/minor and how about the changelog etc…

If @Ashot-KR won’t get to it till tonight, I will take another look.

**Comment by Ashot-KR** [comment]
I'll do it today, but later

**Comment by lukastaegert** [comment]
> I don’t really know if this is a patch/minor

Technically the peerDependency version of Rollup was updated which would make it a major but I think this change is unnecessary as no code changes were included that warrant this. I will change it back to the old peerDependency version range so that we can release it as a patch.

**Comment by Ashot-KR** [comment]
published as 2.2.2
