### ISSUE TITLE
"Error: EEXIST: file already exists" since last update

### ISSUE THREAD

**Issue by lazka** [rollup/rollup-plugin-url#26]
Since the last update I get this error during rollup build, downgrading rollup-plugin-url
 to 2.2.2 fixes things.

```
[!] (plugin at position 7) Error: EEXIST: file already exists, mkdir 'dist'
Error: EEXIST: file already exists, mkdir 'dist'
```

**Comment by lazka** [comment]
Likely because I'm using nodejs 8.10 from Ubuntu 18.04 which doesn't have the recursive option. If that version isn't supported feel free to close.

**Comment by Ashot-KR** [comment]
Ooops… Sorry about that.
Looks like node 8.x maintenance [will be closed in December](https://github.com/nodejs/Release#release-schedule), so i think we already can drop maintenance for node 8. Anyway thanks.

I'll keep this issue opened to not to forget about this

**Comment by lazka** [comment]
No problem, sounds good, thanks!

**Comment by Ashot-KR** [comment]
v3.0.0 with dropped node 8 support and migrated to MIT license published
