### ISSUE TITLE
Should be limited to 14kb by default.

### ISSUE THREAD

**Issue by Shyam-Chen** [rollup/rollup-plugin-url#6]

**Comment by Ashot-KR** [comment]
What do you mean?
Default `limit` option value is `undefined` and all imported files bundles as data-uri.
Can you provide some more info on this, please?

**Comment by Shyam-Chen** [comment]
Should be limited to 14kb by default.

**Comment by Ashot-KR** [comment]
I published new version with limit defaults to `14kb`.
But why `14kb`? File encoded in base64 is 33% larger than file on disk. So in fact size of encoded image will be `18.6kb` (against `14kb` on disk).
Anyway i'll keep `14kb` as limit for now. Maybe this value will be decreased in the future.

**Comment by Shyam-Chen** [comment]
### Reference:
* https://github.com/postcss/postcss-url
* https://github.com/G33kLabs/gulp-inline-base64

**Comment by Ashot-KR** [comment]
@Shyam-Chen thanks!
