### ISSUE TITLE
ability to generate url but not copy file

### ISSUE THREAD

**Issue by DylanPiercey** [rollup/rollup-plugin-url#8]
Currently I am trying to create an isomorphic build using rollup. For the client build this module works perfectly however for the server build I only need it to generate the url (or inline the file if small enough), not do anything with files that are too large since the client side build already handles that.

Webpacks [file-loader](https://github.com/webpack-contrib/file-loader) has this functionality via an 'emitFile' option.

**Comment by Ashot-KR** [comment]
1.2.0 published
